<?php

/**
 * @file
 * Module installation code.
 */

/**
 * Implements hook_uninstall().
 */
function administration_language_negotiation_uninstall() {
  $config = \Drupal::configFactory()->getEditable('language.types');
  $language_types = \Drupal::languageManager()->getLanguageTypes();
  foreach ($language_types as $type) {
    $config->clear('negotiation.' . $type . '.enabled.' . LanguageNegotiationAdministrationLanguage::METHOD_ID);
  }
  $config->save();
}
